// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_the_skateboards: dynamic(() => import("./AboutTheSkateboards")),
  hero: dynamic(() => import("./Hero")),
  product_grid: dynamic(() => import("./ProductGrid")),
};
